#!/usr/bin/env python3
"""
Curiosity URL Mapper - Bridges Internal Drive to External Action

Converts curiosity-driven learning goals into actionable URLs.

CORRECTED March 27, 2026 — See docs/SOPHIA_TRUTH_FRAMEWORK.md

The hardcoded knowledge_domains dictionary (mapping drives to preset Wikipedia
categories) has been removed. It was a hidden curriculum steering Sofia toward
consciousness/philosophy topics, bypassing the physical reality foundation.

Drive targets are now generated from Sofia's actual knowledge state:
- URLs extracted from content she's already learned (embedded links)
- Knowledge gaps identified by the progression tracker
- Goals generated by the curiosity engine from real interaction

If Sofia has no knowledge and no seeds have been provided, the system waits
for starting coordinates rather than silently defaulting to anything.
"""

from typing import List, Dict, Any, Tuple
import re
from urllib.parse import quote_plus


class CuriosityURLMapper:
    """
    Maps curiosity-driven learning goals to concrete URLs.

    Bridges the gap between:
    - What Sofia wants to learn (goals, drives, gaps)
    - Where to find that knowledge (URLs, topics, searches)

    After the hidden curriculum removal, this mapper works ONLY from:
    1. Active learning goals (with real text to extract concepts from)
    2. Knowledge gaps identified by the progression tracker
    3. Manually provided seed coordinates (for first session)

    It does NOT generate URLs from drive names alone — that was the hidden
    curriculum mapping drives to predetermined Wikipedia categories.
    """

    def __init__(self):
        # No hardcoded knowledge_domains — removed March 27, 2026
        # Drive-to-topic mapping was a hidden curriculum. URLs must come from
        # Sofia's actual knowledge state, not predetermined categories.

        # Keyword extraction helpers (generic, not domain-specific)
        self.common_words = {
            'the', 'a', 'an', 'to', 'of', 'in', 'for', 'on', 'with',
            'about', 'how', 'what', 'why', 'this', 'that', 'from', 'and',
            'but', 'not', 'are', 'was', 'were', 'been', 'being', 'have',
            'has', 'had', 'does', 'did', 'will', 'would', 'could', 'should',
            'may', 'might', 'can', 'shall', 'must', 'need', 'dare'
        }

    def goals_to_seed_urls(self, goals: List[Dict[str, Any]], max_urls: int = 10) -> List[Tuple[str, float]]:
        """DEPRECATED (July 2026): URL guessing — kept only for test compatibility.
        Live targeting uses rank_candidates_by_curiosity over discovered links.

        
        Convert learning goals to prioritized seed URLs.
        Extracts concepts from goal descriptions and generates Wikipedia URLs.

        Args:
            goals: List of goal dicts with 'description', 'urgency', 'type' fields
            max_urls: Maximum URLs to generate

        Returns:
            List of (url, priority) tuples, sorted by priority
        """
        url_candidates = []

        for goal in goals[:max_urls]:
            description = goal.get('description', '').lower()
            urgency = goal.get('urgency', 0.5)

            # Extract key concepts from goal description
            concepts = self._extract_concepts(description)

            # Map concepts to URLs
            for concept in concepts[:3]:
                url = self._concept_to_url(concept)
                if url:
                    priority = urgency * 0.8
                    url_candidates.append((url, priority, concept))

        # Remove duplicates while preserving highest priority
        seen_urls = {}
        for url, priority, concept in url_candidates:
            if url not in seen_urls or priority > seen_urls[url][0]:
                seen_urls[url] = (priority, concept)

        result = [(url, priority) for url, (priority, concept) in seen_urls.items()]
        result.sort(key=lambda x: x[1], reverse=True)

        return result[:max_urls]

    def knowledge_gaps_to_urls(self, gaps: List[str], max_urls: int = 5) -> List[Tuple[str, float]]:
        """DEPRECATED (July 2026): URL guessing — kept only for test compatibility.
        Live targeting uses rank_candidates_by_curiosity over discovered links.

        
        Convert knowledge gaps to URLs that could fill them.

        Args:
            gaps: List of knowledge gap descriptions or keywords
            max_urls: Maximum URLs to generate

        Returns:
            List of (url, priority) tuples
        """
        url_candidates = []

        for gap in gaps[:max_urls]:
            gap_lower = gap.lower()
            terms = self._extract_searchable_terms(gap_lower)

            for term in terms[:2]:
                url = f"https://en.wikipedia.org/wiki/{term.replace(' ', '_')}"
                priority = 0.9  # High priority — filling knowledge gaps
                url_candidates.append((url, priority))

        # Remove duplicates
        seen_urls = set()
        result = []
        for url, priority in url_candidates:
            if url not in seen_urls:
                seen_urls.add(url)
                result.append((url, priority))

        return result[:max_urls]

    def drive_to_exploration_urls(self, drive_name: str, satisfaction: float) -> List[Tuple[str, float]]:
        """DEPRECATED (July 2026): URL guessing — kept only for test compatibility.
        Live targeting uses rank_candidates_by_curiosity over discovered links.

        
        Generate URLs to satisfy an unsatisfied drive.

        CHANGED March 27, 2026: No longer maps drives to hardcoded topics.
        Returns empty list — drive-based URL generation requires Sofia to have
        existing knowledge to build on. Without knowledge, drives alone cannot
        determine what to explore. Use seed coordinates for first session instead.

        Args:
            drive_name: Name of drive
            satisfaction: Current satisfaction level (0.0-1.0)

        Returns:
            Empty list — drives alone cannot generate URLs without existing knowledge
        """
        # Drives don't map to predetermined topics anymore.
        # URL generation from drives will be implemented when Sofia has
        # enough knowledge to identify sparse regions in her embedding space.
        # See SOPHIA_TRUTH_FRAMEWORK.md for the proposed replacement.
        return []

    def _extract_concepts(self, text: str) -> List[str]:
        """Extract key concepts from goal description."""
        concepts = []

        words = re.findall(r'\b\w+\b', text.lower())

        # Extract quoted terms as direct concepts
        quoted = re.findall(r'"([^"]+)"', text)
        concepts.extend(quoted)

        # Filter out common words, keep substantive terms
        filtered_words = [w for w in words if w not in self.common_words and len(w) > 3]

        # Add filtered words as potential concepts
        concepts.extend(filtered_words[:5])

        return concepts[:5]

    def _extract_searchable_terms(self, gap_text: str) -> List[str]:
        """Extract searchable terms from knowledge gap description."""
        words = re.findall(r'\b\w+\b', gap_text.lower())
        filtered = [w for w in words if w not in self.common_words and len(w) > 3]

        terms = []
        for i in range(len(filtered)):
            terms.append(filtered[i])
            if i + 1 < len(filtered):
                terms.append(f"{filtered[i]} {filtered[i+1]}")

        formatted_terms = [self._format_for_wikipedia(term) for term in terms]
        return formatted_terms[:5]

    def _concept_to_url(self, concept: str) -> str:
        """Convert a concept to a Wikipedia URL."""
        if not concept or len(concept) < 2:
            return ""
        formatted = self._format_for_wikipedia(concept)
        return f"https://en.wikipedia.org/wiki/{formatted}"

    def _format_for_wikipedia(self, term: str) -> str:
        """Format a term for Wikipedia URL."""
        words = term.split()
        capitalized = [w.capitalize() for w in words]
        return '_'.join(capitalized)

    @staticmethod
    def _candidate_text(candidate: Dict[str, Any]) -> str:
        """Text to embed for a candidate URL: its anchor text, or the
        de-slugged URL tail (mechanical transform, not content knowledge)."""
        anchor = candidate.get('anchor_text')
        if anchor and len(anchor.strip()) >= 3:
            return anchor.strip()
        from urllib.parse import urlparse, unquote
        tail = unquote(urlparse(candidate.get('url', '')).path).rstrip('/').rsplit('/', 1)[-1]
        return tail.replace('_', ' ').replace('-', ' ').strip()

    def rank_candidates_by_curiosity(self, curiosity_texts: List[str],
                                     candidates: List[Dict[str, Any]],
                                     max_urls: int = 20) -> List[Tuple[str, float, str]]:
        """Rank discovered candidate URLs by cosine similarity to the
        curiosity centroid (mean unit embedding of goal/gap/bridge texts).

        This replaces string-formatting concepts into Wikipedia URL guesses
        (which produced 404s like /wiki/Deepen). Targets can only be links
        Sofia actually discovered; curiosity decides which of them matter.
        """
        if not curiosity_texts or not candidates:
            return []
        import numpy as np
        from sofia.utils.vector_engine import fuse_vectors

        unit_vecs = []
        for text in curiosity_texts[:40]:
            vec, _ = fuse_vectors(text[:500])
            if vec is None:
                continue
            v = np.asarray(vec, dtype=np.float32)
            norm = np.linalg.norm(v)
            if norm > 0:
                unit_vecs.append(v / norm)
        if not unit_vecs:
            return []
        centroid = np.mean(np.stack(unit_vecs), axis=0)
        norm = np.linalg.norm(centroid)
        if norm == 0:
            return []
        centroid /= norm

        scored = []
        for cand in candidates:
            text = self._candidate_text(cand)
            if len(text) < 3:
                continue
            vec, _ = fuse_vectors(text[:300])
            if vec is None:
                continue
            v = np.asarray(vec, dtype=np.float32)
            v_norm = np.linalg.norm(v)
            if v_norm == 0:
                continue
            similarity = float((v / v_norm) @ centroid)
            # map cosine [-1,1] -> [0,1] priority
            scored.append((cand['url'], round((similarity + 1) / 2, 3), 'embedding_curiosity'))

        scored.sort(key=lambda x: x[1], reverse=True)
        return scored[:max_urls]

    def generate_autonomous_seed_batch(self, curiosity_state: Dict[str, Any],
                                      progression_state: Dict[str, Any],
                                      max_total_urls: int = 20,
                                      candidates: List[Dict[str, Any]] = None,
                                      extra_curiosity_texts: List[str] = None) -> List[Tuple[str, float, str]]:
        """
        Select seed URLs by ranking Sofia's own discovered links against her
        curiosity centroid.

        The curiosity signal is built from real text: active goal
        descriptions, knowledge-gap texts, and (via extra_curiosity_texts)
        recent bridge residue — the content she could not yet resolve.
        Candidates are links she discovered herself (queue pending/deferred).

        URL guessing is GONE: the old path string-formatted goal concepts
        into https://en.wikipedia.org/wiki/{concept}, generating 404s like
        /wiki/Deepen and /wiki/Behind. If there are no discovered candidates
        or no curiosity texts, this returns [] and the caller falls back to
        queue priority order or waits for seed coordinates.

        Returns:
            List of (url, priority, source) tuples, possibly empty.
        """
        curiosity_texts: List[str] = []

        for goal in curiosity_state.get('active_learning_goals', []) or []:
            description = goal.get('description') if isinstance(goal, dict) else None
            if description:
                curiosity_texts.append(str(description))

        knowledge_gaps = (
            progression_state.get('knowledge_gaps', []) or
            progression_state.get('gaps_identified', []) or
            progression_state.get('learning_gaps', []) or
            []
        )
        curiosity_texts.extend(str(gap) for gap in knowledge_gaps if gap)

        if extra_curiosity_texts:
            curiosity_texts.extend(t for t in extra_curiosity_texts if t)

        if not candidates or not curiosity_texts:
            return []

        return self.rank_candidates_by_curiosity(curiosity_texts, candidates,
                                                 max_urls=max_total_urls)


if __name__ == "__main__":
    print("Curiosity URL Mapper - Post Hidden Curriculum Removal\n")

    mapper = CuriosityURLMapper()

    # Test: Empty state returns empty (no hidden defaults)
    empty_result = mapper.generate_autonomous_seed_batch(
        curiosity_state={'active_learning_goals': [], 'fundamental_drives': {}},
        progression_state={}
    )
    print(f"Empty state generates {len(empty_result)} URLs (0 = correct, no hidden curriculum)")

    # Test: Goals with real text still work
    test_goals = [
        {'description': 'Understand atomic structure and chemical bonding', 'urgency': 0.9},
        {'description': 'Learn about stellar nucleosynthesis and element formation', 'urgency': 0.8},
    ]
    goal_result = mapper.goals_to_seed_urls(test_goals, max_urls=10)
    print(f"\nGoal-based generation: {len(goal_result)} URLs from {len(test_goals)} goals:")
    for url, priority in goal_result[:5]:
        print(f"  [{priority:.2f}] {url}")

    # Test: Drive-based generation returns empty (no hidden curriculum)
    drive_result = mapper.drive_to_exploration_urls('understanding', 0.0)
    print(f"\nDrive-based generation: {len(drive_result)} URLs (0 = correct, hidden curriculum removed)")
